package com.shipment.shipmentservice.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name="SHIPMENT")
public class Shipment {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private Long shipmentId;   
	
	@Column(name="CUSTOMER_ID" , nullable = false)
	private Long customerId;
	
	@Column(name="TRACKING_NUMBER" , nullable = false,unique = true)
	private String trackingNumber;
	
	@Column(name="SENDER_NAME" , nullable = false)
	private String senderName;
	
	@Column(name="SENDER_PHONE" , nullable = false)
	private String senderPhone;
	
	@Column(name="RECEIVER_NAME" , nullable = false)
	private String receiverName;
	
	@Column(name="RECEIVER_PHONE" , nullable = false)
	private String receiverPhone;
	
	@Column(name="PICKUP_ADDRESS" , nullable = false)
	private String pickupAddress;
	
	@Column(name="DELIVERY_ADDRESS" , nullable = false)
	private String deliveryAddress;
	
	@Column(name="PACKAGE_WEIGHT" , nullable = false)
	private Double packageWeight;
	
	@Column(name="PACKAGE_DESCRIPTION" , nullable = false)
	private String packageDescription;
	
	@Enumerated(EnumType.STRING)
	@Column(name="SHIPMENT_STATUS" , nullable = false)
	private ShipmentStatus shipmentStatus;
	
	@Column(name="CREATED_AT" , nullable = false)
	private LocalDateTime createdAt;
	
	@Column(name="UPDATED_AT" , nullable = false)
	private LocalDateTime updatedAt;

	public Long getShipmentId() {
		return shipmentId;
	}

	public void setShipmentId(Long shipmentId) {
		this.shipmentId = shipmentId;
	}

	public Long getCustomerId() {
		return customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	public String getTrackingNumber() {
		return trackingNumber;
	}

	public void setTrackingNumber(String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}

	public String getSenderName() {
		return senderName;
	}

	public void setSenderName(String senderName) {
		this.senderName = senderName;
	}

	public String getSenderPhone() {
		return senderPhone;
	}

	public void setSenderPhone(String senderPhone) {
		this.senderPhone = senderPhone;
	}

	public String getReceiverName() {
		return receiverName;
	}

	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}

	public String getReceiverPhone() {
		return receiverPhone;
	}

	public void setReceiverPhone(String receiverPhone) {
		this.receiverPhone = receiverPhone;
	}

	public String getPickupAddress() {
		return pickupAddress;
	}

	public void setPickupAddress(String pickupAddress) {
		this.pickupAddress = pickupAddress;
	}

	public String getDeliveryAddress() {
		return deliveryAddress;
	}

	public void setDeliveryAddress(String deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	public Double getPackageWeight() {
		return packageWeight;
	}

	public void setPackageWeight(Double packageWeight) {
		this.packageWeight = packageWeight;
	}

	public String getPackageDescription() {
		return packageDescription;
	}

	public void setPackageDescription(String packageDescription) {
		this.packageDescription = packageDescription;
	}

	public ShipmentStatus getShipmentStatus() {
		return shipmentStatus;
	}

	public void setShipmentStatus(ShipmentStatus shipmentStatus) {
		this.shipmentStatus = shipmentStatus;
	}

	public LocalDateTime getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	public LocalDateTime getUpdatedAt() {
		return updatedAt;
	}

	public void setUpdatedAt(LocalDateTime updatedAt) {
		this.updatedAt = updatedAt;
	}
	
	

	//shipmentId, trackingNumber, shipmentStatus,	createdAt,	updatedAt
	//Those are generated by beckend application only.

	
}
